version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - postgres_volume:/pg_data
    environment:
      - PGDATA=/pg_data
      - POSTGRES_PASSWORD=postgres
